// Generated by tools/maps.py. Edit the ASCII there, then rerun it.
const MAPS = {
"overworld": {
"name": "Norway",
"rows": [
"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
"TMMMMMMMMMMMMMMTTTTTTTTTTTTTTTTTTMMMMMMMMMMMMMMTTMMMMMMMMMMMMMMT",
"TMMMMMMXMMMMMMMTT....b..T...bbbTTMMMMMMEMMMMMMMTTMMMMMMXMMMMMMMT",
"TT.....s.......TT.T.......T.b.bTTnnnnnnsnnnnnn#TTnnnnnnsnnnnnnnT",
"TT.T...s...b...TT....TT.....bbbTTnTnnnnsnnnnnnnTTnn#nnnsnnnnTnnT",
"TT.....s................T.......nnnnnnnsnnnTnnnnnnnnnnnsnnnnnnnT",
"TT.b...ssssssssssssssssssssssssssssssssssnnnnnnnnnnnnnnsnnnnnnnT",
"TT.....s..............f.........nnnnnnnsnnnnnnnnnnnnnnnsnn#nnnnT",
"TTT....s....T.....T......TT.....nnTnnnnsnnnn#nnnnnnnnnnsnnnnnnnT",
"TT.....s.....b.TT....b.......T.TTnnnnnnsnnnnnn#TTnnTnnnsnnnnnnnT",
"TTbb...s.......TT..TT....b.....TTnn#nnnsnnnTnnnTTnnnnnnsnnnnnTnT",
"TT.....s..T....TT.......T...T..TTnnnnnnsnnnnnnnTTnnn#nnsnnnnnnnT",
"TT.....s.......TTT..b..........TTnnnnnTsnnnnnnnTTnnnnnnsnnnnnnnT",
"TTTTTT.s..TTTTTTTTTTTT.s..TTTTTTTTTTTT.s..TTTTTTTTTTTT.s..TTTTTT",
"TTTTTT.s..TTTTTTTTTTTT.s..TTTTTTTTTTTT.s..TTTTTTTTTTTT.s..TTTTTT",
"TT.....s.......TT......s.......TT.....ss.......TT#.....s....lllT",
"TTRRRRR.s......TT..RRRRRR......TT..sssssssssss.TT..#...s...lMMMT",
"TTRRRRR.s..RRRRTT..RRRRRR...f..TT..s~~~~~~~~~s.TT......s...lMXMT",
"TTHHDHH.s..RRRRTT..HHHHHH......TT..s~~~~~~~~~s.TT....#.s...lMsMT",
"TT......s..HHDHTT..xQ.Q.Qx.........s~~~~~~~~~s.........s....ssTT",
"TTff....sssssssssssssssssssssss.ssss~~~~~~~~~sssssssssssssssssTT",
"TT......s...............s..........s~~~~~~~~~s.........s......TT",
"TT.x.x..s..f.......f....s..........s~~~~~~~~~s.....#...s...#..TT",
"TT......s.......T.......s....b.TT..s~~~~~~~~~s.TT......s......TT",
"TT.b....s....b.TT..b....s......TT..sssssssssss.TT.#....s....#.TT",
"TT......s......TT.......s......TT......s.......TT......s......TT",
"TT......s......TT.......s......TT..T...s....T..TT......s..#...TT",
"TTTTTT.s..TTTTTTTTTTTT.s..TTTTTTTTTTTT.s..TTTTTTTTTTTT.s..TTTTTT",
"TTTTTT.s..TTTTTTTTTTTT.s..TTTTTTTTTTTT.s..TTTTTTTTTTTT.s..TTTTTT",
"TT.....s.......TT......s.......TT..ss..s..ss...TT......s......TT",
"TT.b...s.......TT......s.......TT.sssssssssss..TT.+.+.+s+.+.+.TT",
"TT.....s...f...TT......s..qq...TT.sssssssssss..TT......s......TT",
"TT.....s.......TT.PPPPPPPPPPPP.TT.sssssssssss..TT.+.+.+s+.+.+.TT",
"TT.....s..........PPPPPPPPPPPP....sssssssssss..........s......TT",
"TT.....ssssssssssssssssssqqssss.sssssssssssssss.sssssssss.....TT",
"Twwwww.s..................s.......sssssssssss...T......s......TT",
"TwwwwwUUU......T....ssssssss....T.sssssssssss..TT.+.+..s..+.+.TT",
"Twwwwwwww.b....TT..............TT.sssssssssss..TT......s......TT",
"TwwwwwwwwwT....TT..b....f......TT..sssssssss...TT.+.+..s..+.+.+T",
"TwwwwwwwwwwT...TT......T.......TT..............TT......s......TT",
"TwwwwwwwwwwwTTTTTTTTTTTTTTTbTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
],
"ents": [
{
"t": "start",
"at": [
24,
36
]
},
{
"t": "runestone",
"at": [
20,
36
]
},
{
"t": "sign",
"at": [
28,
36
],
"text": "sign_airstrip"
},
{
"t": "cargo",
"at": [
29,
33
]
},
{
"t": "npc",
"id": "astrid",
"at": [
5,
20
]
},
{
"t": "npc",
"id": "lars",
"at": [
23,
19
]
},
{
"t": "shop",
"item": "juice",
"price": 40,
"at": [
20,
19
]
},
{
"t": "shop",
"item": "shard",
"price": 25,
"at": [
22,
19
]
},
{
"t": "shop",
"item": "heart3",
"price": 10,
"at": [
24,
19
]
},
{
"t": "npc",
"id": "sven",
"at": [
28,
23
]
},
{
"t": "npc",
"id": "ingrid",
"at": [
9,
36
]
},
{
"t": "sign",
"at": [
10,
21
],
"text": "sign_fjordvik"
},
{
"t": "runestone",
"at": [
42,
4
]
},
{
"t": "sign",
"at": [
41,
3
],
"text": "sign_cavern"
},
{
"t": "sealed",
"at": [
7,
2
],
"text": "seal_barrow"
},
{
"t": "sealed",
"at": [
55,
2
],
"text": "seal_peak"
},
{
"t": "sealed",
"at": [
61,
17
],
"text": "seal_forge"
},
{
"t": "sign",
"at": [
38,
37
],
"text": "sign_beach"
},
{
"t": "warp",
"at": [
39,
2
],
"to": "cavern",
"dest": [
24,
54
]
},
{
"t": "piece",
"id": "hp_forest",
"at": [
29,
3
]
},
{
"t": "piece",
"id": "hp_grave",
"at": [
61,
39
]
},
{
"t": "chest",
"id": "c_coast",
"at": [
14,
30
],
"item": "kr20"
},
{
"t": "penguin",
"at": [
37,
31
]
},
{
"t": "penguin",
"at": [
42,
32
]
},
{
"t": "penguin",
"at": [
39,
36
]
},
{
"t": "penguin",
"at": [
36,
7
]
},
{
"t": "penguin",
"at": [
44,
9
]
},
{
"t": "penguin",
"at": [
58,
6
]
},
{
"t": "wisp",
"at": [
53,
10
]
},
{
"t": "draugr",
"at": [
20,
8
]
},
{
"t": "wisp",
"at": [
27,
10
]
},
{
"t": "draugr",
"at": [
52,
33
]
},
{
"t": "draugr",
"at": [
59,
37
]
},
{
"t": "wisp",
"at": [
55,
39
]
},
{
"t": "wisp",
"at": [
10,
9
]
},
{
"t": "penguin",
"at": [
4,
11
]
},
{
"t": "draugr",
"at": [
57,
23
]
},
{
"t": "wisp",
"at": [
52,
17
]
},
{
"t": "penguin",
"at": [
33,
23
]
}
],
"outdoor": true
},
"cavern": {
"name": "Penguin Ice Cavern",
"rows": [
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWt____________tWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWt____________tWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWWWWhhWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWWWWKKWWWWWWWWWWWWWWWWWWWWWWW",
"Wt____________tWWt____________tWWt____________tW",
"W______________WW______________WW______________W",
"W______________WWvvvvvvGGvvvvvvWW__iiiiiiiiii__W",
"W______________WWvvvvvvGGvvvvvvWW__iiiiiiiiii__W",
"W______________WWvvvvvvGGvvvvvvWW__iiiiiiiiii__W",
"W______________WWvvvvvvGGvvvvvvWW__iiiiiiiiii__W",
"W______________WWvvvvvvGGvvvvvvWW__iiiiiiiiii__W",
"W______________WW______________WW__iiiiiiiiii__W",
"W______________________________Lh__iiiiiiiiii__W",
"W______________________________Lh__iiiiiiiiii__W",
"W______________WW______________WW______________W",
"Wt____________tWWt____________tWWt____________tW",
"WWWWWWWWWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWWWWWWWWWWW",
"Wt____________tWWt____________tWWt____________tW",
"W_O__O_________WW______________WW_vvvvvvvvvv_v_W",
"W______________WW__iiiiiiiiii__WW_vvvvvvvvvv_v_W",
"W______________WW__iiiiiiiiii__WW_vvv________v_W",
"W______________WW__iiiiiiiiii__WW_vvv_vvvvvvvv_W",
"W__________________iiiiiiiiii_________vvvv_____W",
"W__________________iiiiiiiiii_________vvvvvvvv_W",
"W______________WW__iiiiiiiiii__WW_vvvvvvvvvvvv_W",
"W_O__O_________WW__iiiiiiiiii__WW_vvvvvvvvvvvv_W",
"W______________WW__iiiiiiiiii__WW______________W",
"W______________WW______________WW______________W",
"Wt____________tWWt____________tWWt____________tW",
"WWWWWWWWWWWWWWWWWWWWWWW__WWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWWWW__WWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWt____________tWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWt____________tWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWWWW__WWWWWWWWWWWWWWWWWWWWWWW"
],
"ents": [
{
"t": "warp",
"at": [
23,
55
],
"to": "overworld",
"dest": [
39,
3
]
},
{
"t": "warp",
"at": [
24,
55
],
"to": "overworld",
"dest": [
39,
3
]
},
{
"t": "runestone",
"at": [
20,
48
]
},
{
"t": "sign",
"at": [
26,
48
],
"text": "sign_cavern_in"
},
{
"t": "penguin",
"at": [
21,
33
]
},
{
"t": "penguin",
"at": [
26,
33
]
},
{
"t": "penguin",
"at": [
24,
37
]
},
{
"t": "bat",
"at": [
5,
33
]
},
{
"t": "bat",
"at": [
10,
36
]
},
{
"t": "bat",
"at": [
7,
38
]
},
{
"t": "chest",
"id": "cv_key1",
"at": [
7,
34
],
"item": "key",
"clear": true
},
{
"t": "bat",
"at": [
44,
32
]
},
{
"t": "bat",
"at": [
36,
39
]
},
{
"t": "chest",
"id": "cv_key2",
"at": [
44,
30
],
"item": "key"
},
{
"t": "switch",
"id": "cv_gate",
"at": [
18,
15
]
},
{
"t": "draugr",
"at": [
5,
18
]
},
{
"t": "draugr",
"at": [
10,
22
]
},
{
"t": "penguin",
"at": [
7,
25
]
},
{
"t": "chest",
"id": "cv_bigkey",
"at": [
7,
20
],
"item": "bigkey",
"clear": true
},
{
"t": "knight",
"at": [
41,
19
]
},
{
"t": "chest",
"id": "cv_homing",
"at": [
40,
21
],
"item": "homing",
"clear": true
},
{
"t": "king",
"at": [
24,
5
]
},
{
"t": "chest",
"id": "cv_thunder",
"at": [
24,
4
],
"item": "thunder",
"clear": true
},
{
"t": "container",
"id": "hc_cavern",
"at": [
22,
7
],
"clear": true
},
{
"t": "warp",
"at": [
26,
7
],
"to": "overworld",
"dest": [
39,
4
],
"clear": true,
"portal": true
}
],
"dungeon": true
},
"home": {
"name": "Owen's Room, New York",
"rows": [
"ZZZZZZZZZZZZZZZZ",
"ZFFFFFFFFFFFFFFZ",
"ZFYYFFFFFFFQQQFZ",
"ZFYYFFFFFFFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFFFFrrrrrFFFFFZ",
"ZFFFFrrrrrFFFFFZ",
"ZFFFFrrrrrFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFQFFFFFFFFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZZZZZZZddZZZZZZZ"
],
"ents": [
{
"t": "start",
"at": [
3,
4
]
},
{
"t": "plaque",
"at": [
12,
2
]
},
{
"t": "sign",
"at": [
2,
10
],
"text": "sign_poster"
},
{
"t": "flight",
"at": [
7,
13
]
},
{
"t": "flight",
"at": [
8,
13
]
}
]
},
"arena": {
"name": "Valhalla Arena",
"rows": [
"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"Vaaaaaaaaaaaaaa##aaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"Vaaaaaa#aaaaaaaaaaaaaaaa#aaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"Vaaaaaa#aaaaaaaaaaaaaaaa#aaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"Vaaaaaaaaaaaaaa##aaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
],
"ents": [],
"arena": true
}
};
