// Generated by tools/maps.py. Edit the ASCII there, then rerun it.
const MAPS = {
"overworld": {
"name": "Norway",
"rows": [
"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
"TMMMMMMMMMMMMMMTTTTTTTTTTTTTTTTTTMMMMMMMMMMMMMMTTMMMMMMMMMMMMMMT",
"TMMMMMMXMMMMMMMTT,,,,b%%%%,,bbbTTMMMMMMEMMMMMMMTTMMMMMMXMMMMMMMT",
"TT.....s.......TT,T,,%%%%%,T,b,TTnnnnnnsnnnnnn#TTnnnnnnsnnnnnnnT",
"TT.T...s...b...TT,,,,TT%%%,,bbbTTnTnnnnsnnnnnnnTTnn#nnnsnnnnTnnT",
"TT.....s........,,%%%%%%%%,,,,,onnnnnnnsnnnTnnnnnnnnnnnsnnnnnnnT",
"TT.b...sssssssssss%%%%%%%%sssssosssssssssnnnnnnnnnnnnnnsnnnnnnnT",
"TT.....s........%%%%%%%f%%%%,,,Tnnnnnnnsnnnnnnnnnnnnnnnsnn#nnnnT",
"TTT....s....T...%%T%%%%%%TT%%,,TnnTnnnnsnnnn#nnnnnnnnnnsnnnnnnnT",
"TT.....s.....b.TT%%%%b%%%%%%%T,TTnnnnnnsnnnnnn#TTnnTnnnsnnnnnnnT",
"TTbb...s.......TT,,TT%%%%b,,,,,TTnn#nnnsnnnTnnnTTnnnnnnsnnnnnTnT",
"TT.....s..T....TT,,,,,%%T,,,T,,TTnnnnnnsnnnnnnnTTnnn#nnsnnnnnnnT",
"TT.....s.......TTT,,b,,,,,,,,,,TTnnnnnTsnnnnnnnTTnnnnnnsnnnnnnnT",
"TTTTTT.s..TTTTTTTTTTTT,s,,TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
"TTTTTT.s..TTTTTTTTTTTT.s..TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
"TT.....s.......TT......s.......TT.....ss.......TT#.....s....lllT",
"TTRRRRR.s......TT..RRRRRR......TT..sssssssssss.TT..#...s...lMMMT",
"TTRRRRR.s..RRRRTT..RRRRRR...f..TT..s~~~~~~~~~s.TT......s...lMXMT",
"TTHHDHH.s..RRRRTT..HHHHHH......TT..s~~~~~~~~~s.TT....#.s...lMsMT",
"TT......s..HHDHTT..xQ.Q.Qx.........s~~~~~~~~~s.........s....ssTT",
"TTff....sssssssssssssssssssssss.ssss~~~~~~~~~sssssssssssssssssTT",
"TT......s...............s..........s~~~~~~~~~s.........s......TT",
"TT.x.x..s..f.......f....s..........s~~~~~~~~~s.....#...s...#..TT",
"TT......s....,,.T.......s....b.TT..s~~~~~~~~~s.TT......s......TT",
"TT.b....s....b,TT..b....s......TT..sssssssssss.TT.#....s....#.TT",
"T,,.....s....,,TT.......s......TT......s.......TT......s......TT",
"T,,,....s......TT.......s......TT..T...s....T..TT......s..#...TT",
"TTTTTT.s..TTTTTTTTTTTT.s..TTTTTTTTTTTT.s..TTTTTTTTTTTT.s..TTTTTT",
"TTTTTT.s..TTTTTTTTTTTT.s..TTTTTTTTTTTT.s..TTTTTTTTTTTT.s..TTTTTT",
"TT.....s.......TT......s.......TT..ss..s..ss...TT......s......TT",
"TT.b...s.......TT......s.......TT.sssssssssss..TT.+.+.+s+.+.+.TT",
"TT.....s...f...TT......s..qq...TT.sssssssssss..TT......s......TT",
"TT.....s.......TT.PPPPPPPPPPPP.TT.sssssssssss..TT.+.+.+s+.+.+.TT",
"TT.....s..........PPPPPPPPPPPP....sssssssssss..........s......TT",
"TT.....ssssssssssssssssssqqssss.sssssssssssssss.sssssssss.....TT",
"Twwwww.s..................s.......sssssssssss...T......s......TT",
"TwwwwwUUU......T....ssssssss....T.sssssssssss..TT.+.+..s..+.+.TT",
"Twwwwwwww.b....TT..s...........TT.sssssssssss..TT......s......TT",
"TwwwwwwwwwT....TT..>....f......TT..sssssssss...TT.+.+..s..+.+.+T",
"TwwwwwwwwwwT...TT......T.......TT..............TT......s......TT",
"TwwwwwwwwwwwTTTTTTTTTTTTTTTbTTTTTTTTTTTTTTTTTTTTT.TTTTTTTTTTTTTT",
"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
],
"ents": [
{
"t": "start",
"at": [
24,
36
]
},
{
"t": "runestone",
"at": [
20,
36
]
},
{
"t": "sign",
"at": [
28,
36
],
"text": "sign_airstrip"
},
{
"t": "cargo",
"at": [
29,
33
]
},
{
"t": "npc",
"id": "attendant_ok",
"at": [
21,
35
]
},
{
"t": "warp",
"at": [
19,
38
],
"to": "subway",
"dest": [
8,
3
]
},
{
"t": "sign",
"at": [
18,
37
],
"text": "sign_subway"
},
{
"t": "taxi",
"at": [
23,
12
],
"to": "airport"
},
{
"t": "log",
"id": "biglog",
"at": [
31,
5
]
},
{
"t": "spore",
"at": [
22,
3
]
},
{
"t": "spore",
"at": [
27,
8
]
},
{
"t": "slime",
"at": [
20,
7
]
},
{
"t": "slime",
"at": [
28,
10
]
},
{
"t": "beetle",
"at": [
52,
9
]
},
{
"t": "beetle",
"at": [
51,
31
]
},
{
"t": "tablet",
"id": "tab_coast",
"at": [
2,
31
]
},
{
"t": "tablet",
"id": "tab_hills",
"at": [
13,
11
]
},
{
"t": "tablet",
"id": "tab_lake",
"at": [
46,
15
]
},
{
"t": "tablet",
"id": "tab_grave",
"at": [
49,
40
]
},
{
"t": "tablet",
"id": "tab_volcano",
"at": [
49,
15
]
},
{
"t": "tablet",
"id": "tab_snow",
"at": [
61,
12
]
},
{
"t": "tablet",
"id": "tab_village",
"at": [
2,
26
]
},
{
"t": "npc",
"id": "astrid",
"at": [
5,
20
]
},
{
"t": "npc",
"id": "lars",
"at": [
23,
19
]
},
{
"t": "shop",
"item": "juice",
"price": 40,
"at": [
20,
19
]
},
{
"t": "shop",
"item": "shard",
"price": 25,
"at": [
22,
19
]
},
{
"t": "shop",
"item": "heart3",
"price": 10,
"at": [
24,
19
]
},
{
"t": "npc",
"id": "sven",
"at": [
28,
23
]
},
{
"t": "npc",
"id": "ingrid",
"at": [
9,
36
]
},
{
"t": "sign",
"at": [
10,
21
],
"text": "sign_fjordvik"
},
{
"t": "runestone",
"at": [
42,
4
]
},
{
"t": "sign",
"at": [
41,
3
],
"text": "sign_cavern"
},
{
"t": "sealed",
"at": [
7,
2
],
"text": "seal_barrow",
"opensWith": "d1done"
},
{
"t": "runedoor",
"at": [
7,
2
],
"needs": "d1done",
"to": "barrow",
"dest": [
24,
40
]
},
{
"t": "sealed",
"at": [
55,
2
],
"text": "seal_peak"
},
{
"t": "sealed",
"at": [
61,
17
],
"text": "seal_forge"
},
{
"t": "sign",
"at": [
38,
37
],
"text": "sign_beach"
},
{
"t": "warp",
"at": [
39,
2
],
"to": "cavern",
"dest": [
24,
54
]
},
{
"t": "door",
"at": [
4,
18
],
"to": "astrid_house",
"dest": [
7,
12
]
},
{
"t": "door",
"at": [
13,
19
],
"to": "bjarne_house",
"dest": [
7,
12
]
},
{
"t": "qitem",
"id": "sheet",
"at": [
43,
37
],
"needs": "quest_bjarne"
},
{
"t": "qitem",
"id": "ship",
"at": [
21,
9
],
"needs": "quest_sven",
"underBush": true
},
{
"t": "grave",
"at": [
61,
36
]
},
{
"t": "stairs",
"at": [
61,
36
],
"to": "secret_cave",
"dest": [
8,
11
]
},
{
"t": "piece",
"id": "hp_forest",
"at": [
29,
3
]
},
{
"t": "piece",
"id": "hp_grave",
"at": [
61,
39
]
},
{
"t": "chest",
"id": "c_coast",
"at": [
14,
30
],
"item": "kr20"
},
{
"t": "penguin",
"at": [
37,
31
]
},
{
"t": "penguin",
"at": [
42,
32
]
},
{
"t": "penguin",
"at": [
39,
36
]
},
{
"t": "snowpeng",
"at": [
36,
7
]
},
{
"t": "penguin",
"at": [
44,
9
]
},
{
"t": "snowpeng",
"at": [
58,
6
]
},
{
"t": "wisp",
"at": [
53,
10
]
},
{
"t": "snowpeng",
"at": [
51,
11
]
},
{
"t": "draugr",
"at": [
20,
8
]
},
{
"t": "wisp",
"at": [
27,
10
]
},
{
"t": "draugr",
"at": [
52,
33
]
},
{
"t": "draugr",
"at": [
59,
37
]
},
{
"t": "wisp",
"at": [
55,
39
]
},
{
"t": "wisp",
"at": [
10,
9
]
},
{
"t": "penguin",
"at": [
4,
11
]
},
{
"t": "draugr",
"at": [
57,
23
]
},
{
"t": "wisp",
"at": [
52,
17
]
},
{
"t": "penguin",
"at": [
33,
23
]
}
],
"outdoor": true
},
"cavern": {
"name": "Penguin Palace",
"rows": [
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWt____________tWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW_iiiiiiiiiiii_WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWt____________tWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWWWWhhWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWWWWKKWWWWWWWWWWWWWWWWWWWWWWW",
"Wt____________tWWt____________tWWt____________tW",
"W______________WW______________WW______________W",
"W______________WWvvvvvvGGvvvvvvWW__iiiiiiiiii__W",
"W______________WWvvvvvvGGvvvvvvWW__iiiiiiiiii__W",
"W______________WWvvvvvvGGvvvvvvWW__iiiiiiiiii__W",
"W______________WWvvvvvvGGvvvvvvWW__iiiiiiiiii__W",
"W______________WWvvvvvvGGvvvvvvWW__iiiiiiiiii__W",
"W______________WW______________WW__iiiiiiiiii__W",
"W______________________________Lh__iiiiiiiiii__W",
"W______________________________Lh__iiiiiiiiii__W",
"W______________WW______________WW______________W",
"Wt____________tWWt____________tWWt____________tW",
"WWWWWWWWWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWWWWWWWWWWW",
"Wt____________tWWt____________tWWt____________tW",
"W_O__O_________WW______________WW_vvvvvvvvvv_v_W",
"W______________WW__iiiiiiiiii__WW_vvvvvvvvvv_v_W",
"W______________WW__iiiiiiiiii__WW_vvv________v_W",
"W______________WW__iiiiiiiiii__WW_vvv_vvvvvvvv_W",
"W__________________iiiiiiiiii_________vvvv_____W",
"W__________________iiiiiiiiii_________vvvvvvvv_W",
"W______________WW__iiiiiiiiii__WW_vvvvvvvvvvvv_W",
"W_O__O_________WW__iiiiiiiiii__WW_vvvvvvvvvvvv_W",
"W______________WW__iiiiiiiiii__WW______________W",
"W______________WW______________WW______________W",
"Wt____________tWWt____________tWWt____________tW",
"WWWWWWWWWWWWWWWWWWWWWWW__WWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWWWW__WWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWt____________tWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWt____________tWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWWWW__WWWWWWWWWWWWWWWWWWWWWWW"
],
"ents": [
{
"t": "warp",
"at": [
23,
55
],
"to": "overworld",
"dest": [
39,
3
]
},
{
"t": "warp",
"at": [
24,
55
],
"to": "overworld",
"dest": [
39,
3
]
},
{
"t": "runestone",
"at": [
20,
48
]
},
{
"t": "sign",
"at": [
26,
48
],
"text": "sign_cavern_in"
},
{
"t": "penguin",
"at": [
21,
33
]
},
{
"t": "guard",
"at": [
26,
33
]
},
{
"t": "penguin",
"at": [
24,
37
]
},
{
"t": "bat",
"at": [
5,
33
]
},
{
"t": "bat",
"at": [
10,
36
]
},
{
"t": "bat",
"at": [
7,
38
]
},
{
"t": "chest",
"id": "cv_key1",
"at": [
7,
34
],
"item": "key",
"clear": true
},
{
"t": "bat",
"at": [
44,
32
]
},
{
"t": "bat",
"at": [
36,
39
]
},
{
"t": "chest",
"id": "cv_key2",
"at": [
44,
30
],
"item": "key"
},
{
"t": "switch",
"id": "cv_gate",
"at": [
18,
15
]
},
{
"t": "guard",
"at": [
5,
18
]
},
{
"t": "draugr",
"at": [
10,
22
]
},
{
"t": "penguin",
"at": [
7,
25
]
},
{
"t": "chest",
"id": "cv_bigkey",
"at": [
7,
20
],
"item": "bigkey",
"clear": true
},
{
"t": "knight",
"at": [
41,
19
]
},
{
"t": "chest",
"id": "cv_homing",
"at": [
40,
21
],
"item": "homing",
"clear": true
},
{
"t": "king",
"at": [
24,
5
]
},
{
"t": "throne",
"at": [
24,
2
]
},
{
"t": "tablet",
"id": "tab_palace",
"at": [
2,
16
]
},
{
"t": "chest",
"id": "cv_thunder",
"at": [
24,
4
],
"item": "thunder",
"clear": true
},
{
"t": "container",
"id": "hc_cavern",
"at": [
22,
7
],
"clear": true
},
{
"t": "warp",
"at": [
26,
7
],
"to": "overworld",
"dest": [
39,
4
],
"clear": true,
"portal": true
}
],
"dungeon": true,
"palace": true
},
"home": {
"name": "Owen's Room, New York",
"rows": [
"ZZZZZZZZZZZZZZZZ",
"ZFFFFFFFFFFFFFFZ",
"ZFYYFFFFFFFQQQFZ",
"ZFYYFFFFFFFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFFFFrrrrrFFFFFZ",
"ZFFFFrrrrrFFFFFZ",
"ZFFFFrrrrrFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFQFFFFFFFFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZZZZZZZddZZZZZZZ"
],
"ents": [
{
"t": "start",
"at": [
3,
4
]
},
{
"t": "plaque",
"at": [
12,
2
]
},
{
"t": "sign",
"at": [
2,
10
],
"text": "sign_poster"
},
{
"t": "flight",
"at": [
7,
13
]
},
{
"t": "flight",
"at": [
8,
13
]
}
],
"interior": true
},
"arena": {
"name": "Valhalla Arena",
"rows": [
"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"Vaaaaaaaaaaaaaa##aaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"Vaaaaaa#aaaaaaaaaaaaaaaa#aaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"Vaaaaaa#aaaaaaaaaaaaaaaa#aaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"Vaaaaaaaaaaaaaa##aaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaV",
"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
],
"ents": [],
"arena": true
},
"astrid_house": {
"name": "Astrid's House",
"rows": [
"ZZZZZZZZZZZZZZZZ",
"ZkkFFFppFFFFkkFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFFQQFFFFFFFFYYZ",
"ZFFFFFFFFFFFFYYZ",
"ZFFFFrrrrrrFFFFZ",
"ZFFFFrrrrrrFFFFZ",
"ZOFFFrrrrrrFFFOZ",
"ZOFFFFFFFFFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZZZZZZZddZZZZZZZ"
],
"ents": [
{
"t": "sign",
"at": [
10,
0
],
"text": "tapestry"
},
{
"t": "sign",
"at": [
2,
1
],
"text": "bookshelf"
},
{
"t": "chest",
"id": "c_astrid",
"at": [
14,
10
],
"item": "juice"
},
{
"t": "warp",
"at": [
7,
13
],
"to": "overworld",
"dest": [
4,
19
]
},
{
"t": "warp",
"at": [
8,
13
],
"to": "overworld",
"dest": [
4,
19
]
}
],
"interior": true
},
"bjarne_house": {
"name": "Bjarne's House",
"rows": [
"ZZZZZZZZZZZZZZZZ",
"ZkkFFFFFFFFFkkFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFFFFFFFFFFFYYFZ",
"ZFFQQQFFFFFFYYFZ",
"ZFFFFFFFFFFFFFFZ",
"ZFFFFrrrrrrFFFFZ",
"ZFFFFrrrrrrFFFFZ",
"ZFFFFrrrrrrFFFFZ",
"ZFFFFFFFFFFFFFFZ",
"ZOFFFFFFFFFFFFOZ",
"ZFFFFFFFFFFFFFFZ",
"ZZZZZZZddZZZZZZZ"
],
"ents": [
{
"t": "npc",
"id": "bjarne",
"at": [
7,
6
]
},
{
"t": "sign",
"at": [
10,
0
],
"text": "rush_poster"
},
{
"t": "warp",
"at": [
7,
13
],
"to": "overworld",
"dest": [
13,
20
]
},
{
"t": "warp",
"at": [
8,
13
],
"to": "overworld",
"dest": [
13,
20
]
}
],
"interior": true
},
"secret_cave": {
"name": "Hidden Cave",
"rows": [
"CCCCCCCCCCCCCCCC",
"CCCggggCCCggggCC",
"CCggggggggggggCC",
"CgggCCggggCCgggC",
"CggggggggggggggC",
"CggCgggOOgggCggC",
"CgggggggggggggCC",
"CCggggCCCCgggggC",
"CCgggggCCgggggCC",
"CgggggggggggOggC",
"CggCCgggggggggCC",
"CCgggggggggCCgCC",
"CCCggggg<gggCCCC",
"CCCCCCCCCCCCCCCC"
],
"ents": [
{
"t": "chest",
"id": "c_cave",
"at": [
5,
1
],
"item": "piece"
},
{
"t": "bat",
"at": [
4,
4
]
},
{
"t": "bat",
"at": [
11,
8
]
},
{
"t": "wisp",
"at": [
12,
2
]
},
{
"t": "warp",
"at": [
8,
12
],
"to": "overworld",
"dest": [
61,
37
]
},
{
"t": "sign",
"at": [
6,
7
],
"text": "cave_carving"
}
],
"dark": true
},
"subway": {
"name": "Fjordvik T-bane",
"rows": [
"IIIIIIIIIIIIIIII",
"IjjjjjjjjjjjjjjI",
"IjjjjjjjjjjjjjjI",
"IjjjjjjjjjjjjjjI",
"IjjjjjjjjjjjjjjI",
"IjjjjjjjjjjjjjjI",
"IjjjjjjjjjjjjjjI",
"IjjjjjjjjjjjjjjI",
"IjjjjjjjjjjjjjjI",
"IIIIIIIIIIIIIIII",
"::::::::::::::::",
"::::::::::::::::",
"IIIIIIIIIIIIIIII",
"IIIIIIIIIIIIIIII"
],
"ents": [
{
"t": "warp",
"at": [
8,
1
],
"to": "overworld",
"dest": [
19,
37
]
},
{
"t": "exchange",
"at": [
3,
1
]
},
{
"t": "sign",
"at": [
12,
1
],
"text": "sign_tbane"
},
{
"t": "taxi",
"at": [
14,
5
],
"to": "forest"
},
{
"t": "npc",
"id": "commuter",
"at": [
10,
6
]
},
{
"t": "runestone",
"at": [
6,
7
]
}
],
"interior": true
},
"barrow": {
"name": "The Drowned Barrow",
"rows": [
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWww__________wwWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWw____________wWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWW______________WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWw____________wWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWww__________wwWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWWWWhhWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWWWWKKWWWWWWWWWWWWWWWWWWWWWWW",
"Wt____________tWWt____________tWWt___vv_______tW",
"W______________WW______________WW____vv________W",
"W______________WW______________WW____vv________W",
"W______________WWwwwwwwwwwwwwwwWW____vv________W",
"W______________WWwwwwwwwwwwwwwwWW____vv________W",
"W______________h_______________y_____vv________W",
"W______________h_______________y_____vv________W",
"W______________WW______________WW____vv________W",
"W______________WW______________WW____vv________W",
"W______________WW______________WW____vv________W",
"W______________WW______________WW____vv________W",
"Wt____________tWWt____________tWWt___vv_______tW",
"WWWWWWWWWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWWWWWWWWWWW",
"Wt____________tWWt____________tWWt_______ww___tW",
"W______________WW______________WW________ww____W",
"W__w__w________WW______________WW________ww____W",
"W______________WW______________WW________ww____W",
"W______________WW______________WW________ww____W",
"W________________________________________ww____W",
"W________________________________________ww____W",
"W______________WW______________WW________ww____W",
"W__w__w________WW_ww________ww_WW________ww____W",
"W______________WW_ww________ww_WW________ww____W",
"W______________WW______________WW________ww____W",
"Wt____________tWWt____________tWWt_______ww___tW",
"WWWWWWWWWWWWWWWWWWWWWWW__WWWWWWWWWWWWWWWWWWWWWWW"
],
"ents": [
{
"t": "warp",
"at": [
23,
41
],
"to": "overworld",
"dest": [
7,
3
]
},
{
"t": "warp",
"at": [
24,
41
],
"to": "overworld",
"dest": [
7,
3
]
},
{
"t": "runestone",
"at": [
20,
34
]
},
{
"t": "npc",
"id": "fluffy",
"at": [
26,
34
]
},
{
"t": "draugr",
"at": [
5,
33
]
},
{
"t": "draugr",
"at": [
10,
37
]
},
{
"t": "wisp",
"at": [
8,
31
]
},
{
"t": "chest",
"id": "br_key",
"at": [
7,
34
],
"item": "key",
"clear": true
},
{
"t": "bat",
"at": [
36,
32
]
},
{
"t": "bat",
"at": [
37,
38
]
},
{
"t": "chest",
"id": "br_kr",
"at": [
45,
34
],
"item": "kr50"
},
{
"t": "draugr",
"at": [
21,
23
]
},
{
"t": "wisp",
"at": [
26,
16
]
},
{
"t": "captain",
"at": [
6,
20
]
},
{
"t": "chest",
"id": "br_dash",
"at": [
8,
20
],
"item": "dash",
"clear": true
},
{
"t": "wisp",
"at": [
43,
17
]
},
{
"t": "bat",
"at": [
44,
24
]
},
{
"t": "chest",
"id": "br_bigkey",
"at": [
44,
20
],
"item": "bigkey"
},
{
"t": "hank",
"at": [
24,
5
]
},
{
"t": "container",
"id": "hc_barrow",
"at": [
22,
9
],
"clear": true
},
{
"t": "warp",
"at": [
26,
9
],
"to": "overworld",
"dest": [
7,
4
],
"clear": true,
"portal": true
}
],
"dungeon": true
},
"redeye": {
"name": "The Red-Eye",
"rows": [
"uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu",
"uuuuueuuuuuuuuuuuuuuuuuueuuuuuuuuuuuuuuueuuuuuuuuuuueuuuuuueuuuu",
"u==============uumAmAmAmAmAmAmmuumBBmmmmmmmmBBmuummmmmmmmmmmmmmu",
"u===BB======B==uumAmAmAmAmAmAmmuummmmmmmmmmmmmmuummAmmmmmmmmAmmu",
"u===B=======B==uumAmAmAmAmAmAmmuummmmmmmmmmmmmmuummAmmmmmmmmAmmu",
"u==============uummmmJmmmmmmJmmuummmmmmmmmmmmmmuummmmmmmmmmmmmmu",
"d===============mmmmmJmmmmmmmmmmmmmmmmmmmmmmmmmmhmmmmmmmmmmmmmmu",
"d===============mmmmmmmmmJmmmmmmmmmmmmmmmmmmmmmmhmmmmmmmmmmmmmmu",
"u======B=======uummmmmmmmJmmmmmuummmmmmmmmmmmmmuummmmmmmmmmmmmmu",
"u========BB====uumAmAmAmAmAmAmmuummmmmmmmmmmmmmuummAmmmmmmmmAmmu",
"u==B======B==B=uumAmAmAmAmAmAmmuummmmmmmmmmmmmmuummAmmmmmmmmAmmu",
"u==============uumAmAmAmAmAmAmmuumBBmmmmmmmmBBmuummmmmmmmmmmmmmu",
"uuuuueuuuuuuuuuuuuuuuuuueuuuuuuuuuuuuuuueuuuuuuuuuuueuuuuuueuuuu",
"uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"
],
"ents": [
{
"t": "warp",
"at": [
0,
6
],
"to": "overworld",
"dest": [
29,
34
]
},
{
"t": "warp",
"at": [
0,
7
],
"to": "overworld",
"dest": [
29,
34
]
},
{
"t": "imp",
"at": [
8,
4
]
},
{
"t": "imp",
"at": [
11,
7
]
},
{
"t": "imp",
"at": [
23,
6
]
},
{
"t": "imp",
"at": [
27,
7
]
},
{
"t": "wisp",
"at": [
19,
6
]
},
{
"t": "cart",
"at": [
37,
3
]
},
{
"t": "cart",
"at": [
42,
10
]
},
{
"t": "imp",
"at": [
39,
6
]
},
{
"t": "imp",
"at": [
44,
7
]
},
{
"t": "attendant",
"at": [
56,
6
]
},
{
"t": "container",
"id": "hc_redeye",
"at": [
54,
7
],
"clear": true
},
{
"t": "chest",
"id": "c_horn",
"at": [
57,
7
],
"item": "horn",
"clear": true
},
{
"t": "warp",
"at": [
61,
7
],
"to": "overworld",
"dest": [
29,
34
],
"clear": true,
"portal": true
}
],
"dungeon": true,
"dark": true,
"redeye": true,
"nokeys": true
}
};
