// All words in the game. Owen: edit freely. [speaker, text] pairs; speaker '' = narration.
const STORY = {
  intro: [
    ['Jon', 'Get up, you oaf!'],
    ['Owen', 'Oh yeah. Jon is a flying axe that can talk. If you think that\'s weird, he can also recite Rush E note for note, from memory.'],
    ['Jon', 'Come look at the table! I carved you something!'],
  ],
  plaque: [
    ['', '"WORLD\'S BEST OWNER OF A FLYING AND TALKING AXE NAMED JON"'],
    ['Jon', 'Well?'],
    ['Owen', 'Very nice of you Jon, I appreciate it.'],
    ['Jon', 'Are you gonna put it in our room?!?'],
    ['Owen', 'Um, sure...'],
    ['Jon', 'Well, I think we should get going. TO... (dramatic pause...) NORWAY!'],
    ['Owen', 'WHAT?! Norway is where I got you. It\'s also where I was killed and brought back to life.'],
    ['Jon', 'Exactly. Unfinished business. Grab your stuff. Door\'s at the bottom.'],
  ],
  poster: [['', 'A poster of a Viking longship. Under it, in marker: "OWEN\'S ROOM. NO PENGUINS."']],
  flight: [
    { art: 'plane', lines: [['', 'Flight 364. New York to Norway. Jon is in a checked bag down below.'], ['Owen', 'I tried not to think about my last time in Norway.']] },
    { art: 'cabin', lines: [['Attendant', 'Refreshments will come around once we reach a steady flying level.'], ['Owen', '(She gave me an odd look.)']] },
    { art: 'demon', lines: [['Owen', '"DEMON!!" my mind screamed.'], ['Attendant', 'Is everything alright, sir?'], ['Owen', 'Yep...']] },
    { art: 'cabin', lines: [['', 'I fell asleep. My dreams were incredibly weird. One was that I turned into a cow.']] },
    { art: 'demon', lines: [['Attendant', 'Any refreshments, sir?'], ['', 'Her nails grew into talons. Her teeth into fangs.'], ['Attendant', 'Wonderful...'], ['Owen', 'I tried to call Jon.']] },
    { art: 'land', lines: [['', '...and then the wheels hit the runway. Fjordvik, Norway.'], ['Owen', 'Was that a dream? It had to be a dream.']] },
  ],
  arrival: [
    ['Jon', '*thump* Ow. Who packs an axe UNDER a cello? Anyway. NORWAY!'],
    ['Owen', 'Jon. The flight attendant. She had fangs.'],
    ['Jon', 'Probably just the airline food. Look, we have bigger problems. Look at the beach down south.'],
    ['Jon', 'PENGUINS. In NORWAY. Penguins don\'t even LIVE here, Owen. Somebody is possessing them again.'],
    ['Jon', 'Elder Astrid in Fjordvik knows the old stories. Village is north-west of the airstrip.'],
    ['', 'Arrows/WASD move. Z swings Jon or talks. X throws Jon. Enter opens your gear. Touch a runestone to save.'],
  ],
  cargo: [
    ['', 'Something is scratching inside the cargo hold. Slowly. Like long fingernails.'],
    ['', 'A voice whispers your name through the metal. Then it laughs.'],
    ['Jon', 'Nope. Nope nope nope. We are NOT going in there yet. Come back when we are stronger.'],
  ],
  cargo_later: [['Jon', 'The scratching stopped. That is somehow worse. (The Red-Eye side quest arrives in a later chapter.)']],
  astrid_1: [
    ['Astrid', 'So. The boy who pulled Jontuka out of the lake has come back. And still alive. Mostly.'],
    ['Owen', 'Undead voodoo magic zombie, actually.'],
    ['Astrid', 'Hm. Well. Listen. A bizillion years ago, a smith forged that axe in the volcano east of here.'],
    ['Astrid', 'Walther the Wise, we called him. Or was it Waldo? Wilbur? Nobody remembers his real name.'],
    ['Owen', 'I just call him Walter the Wonderful.'],
    ['Astrid', 'Then a Viking chieftain named Hank threw the axe in the lake so only Viking blood could pull it out.'],
    ['Astrid', 'He was hiding it from Chilly, the Frost Demon. Chilly wants Jontuka. With it, he could crack open the volcano and freeze the whole world.'],
    ['Astrid', 'Chilly cannot walk in daylight. So he possesses creatures that do not belong here. Like penguins.'],
    ['Jon', 'Told you.'],
    ['Astrid', 'His penguins nest in the Ice Cavern up the Frozen Path, north-east. Whatever leads them lives at the bottom.'],
    ['Astrid', 'Take this. Every bit of coin helps. Lars at the market sells lingonberry juice. It brings you back from almost anything.'],
  ],
  astrid_2: [['Astrid', 'The Ice Cavern is up the Frozen Path, north-east. Mind the slippery floors. Penguins love ice.']],
  astrid_3: [
    ['Astrid', 'The Thunder Rune! Walter carved that rune for the axe himself. Jontuka remembers who he is.'],
    ['Astrid', 'Chilly will not stop. Three more rune doors are sealed: the Drowned Barrow, Walter\'s Forge, and the Storm Peak.'],
    ['Astrid', 'They will open when the story is ready to be told.'],
  ],
  lars: [['Lars', 'Velkommen! Lingonberry juice, rune shards, hearts. Walk up to a table and press Z to buy.']],
  sven_1: [['Sven', 'My big sister says if you cut bushes with an axe you find kroner. I saw a sparkly thing in the forest behind a ring of bushes.']],
  sven_2: [['Sven', 'There is another sparkly thing in the graveyard. In the far corner. I am NOT going in there.']],
  ingrid: [
    ['Ingrid', 'You swim in the lake, it spits you right back out. Lake\'s got manners, that one.'],
    ['Ingrid', 'Ever since the penguins showed up, I hear them at night. "Ak ak ak."'],
    ['Jon', '...that one was me.'],
  ],
  signs: {
    sign_airstrip: [['', 'FJORDVIK AIRSTRIP. Village: north-west. Lake: north-east. Beach: east.']],
    sign_fjordvik: [['', 'FJORDVIK. Population: 41 Vikings, 0 penguins (we hope).']],
    sign_cavern: [['', 'PENGUIN ICE CAVERN. Turn back. Seriously.']],
    sign_cavern_in: [['', 'Locked doors take a small key. The big door takes the BIG key. Crystals switch things.']],
    sign_beach: [['', 'HERE IS THE BEACH WHERE OWEN DIED. (He got better.)']],
    sign_poster: [['', 'A poster of a Viking longship. Under it, in marker: "OWEN\'S ROOM. NO PENGUINS."']],
    seal_barrow: [['', 'A stone door, sealed by a glowing rune. The DROWNED BARROW. Chapter 2.']],
    seal_forge: [['', 'A stone door, sealed by a glowing rune. WALTER\'S FORGE. Chapter 3.']],
    seal_peak: [['', 'A stone door, sealed by a glowing rune. The STORM PEAK. Chapter 4.']],
  },
  house: [['', 'Nobody answers. Someone inside is humming Rush E.']],
  cavern_enter: [['Jon', 'It\'s FREEZING. Penguins everywhere. Stay off the ice if you like stopping.']],
  pit_first: [['Jon', 'You fell in a hole. I would have flown. Just saying.']],
  locked: [['', 'Locked. You need a small key.']],
  bossdoor: [['', 'A huge door with a huge lock. You need the BIG key.']],
  knight: [['Jon', 'A penguin in ARMOR. Hit him from the side or the back. His shield blocks the front!']],
  king: [
    ['Penguin King', 'AK. AK AK. The axe. Give... me... the AXE.'],
    ['Owen', 'You\'re the one who killed me!'],
    ['Penguin King', 'That was my cousin. I am WORSE. Chilly made me KING.'],
    ['Jon', 'He belly-slides! Dodge him, let him smack the wall, THEN chop him while he\'s dizzy!'],
  ],
  king_down: [
    ['Penguin King', 'Ak... Chilly... will... find you...'],
    ['', 'The frost spirit flies out of the penguin and shatters. A very confused regular penguin waddles away.'],
    ['Jon', 'And THAT is how we do it in Norway.'],
  ],
  tapestry: [['', 'A woven tapestry: a huge Viking in a horned helmet hurls a glowing axe into a lake. Stitched underneath: "HANK DID THIS."']],
  bookshelf: [['', 'A thick book: "WALTER THE WONDERFUL: A Biography." Chapter 1, "His Real Name Was..."'], ['', 'The rest of the page is torn out. Somebody does NOT want you to know.']],
  rush_poster: [['', 'A hand-painted poster: "RUSH Ø. The fastest song ever written. Do not attempt. (Bjarne attempted.)"']],
  cave_carving: [['', 'Scratched into the rock: "FLUFFY WAS HERE. FLUFFY WAS A GOOD BOY." Paw prints run off into the dark.']],
  grave: [['', '"HERE LIES FLUFFY, HANK\'S DOG. GOOD BOY."'], ['Jon', 'Owen. The stone is loose. Push it. Push the dog grave.'], ['', 'The gravestone grinds aside. Stairs lead down into the dark!']],
  grave_open: [['Jon', 'Fluffy\'s secret tunnel. Good boy.']],
  sven_quest: [['Sven', 'Owen! I lost my toy longship in the Whispering Forest, north of the village. I hid it under a bush so the penguins wouldn\'t get it...'], ['Sven', '...and then I forgot which bush. Can you find it? Jon can cut bushes, right?']],
  sven_waiting: [['Sven', 'It\'s under one of the bushes in the forest. I think it\'s near the big path. Probably. Maybe.']],
  sven_thanks: [['Sven', 'MY LONGSHIP! You found it! Here, take my savings. And this juice. Mom says it\'s for emergencies, but this IS one.']],
  bjarne_quest: [['Bjarne', 'Ah, a visitor! I am Bjarne, the greatest musician in Fjordvik. Also the only one.'], ['Bjarne', 'I wrote the fastest song in the world: RUSH Ø. But a penguin sneezed and my sheet music blew all the way to the beach!'], ['Jon', 'Rush Ø? I know a song like that. I can recite it note for note.'], ['Bjarne', 'Then you understand! Please, bring back my music. The beach is south-east, past the lake.']],
  bjarne_waiting: [['Bjarne', 'My sheet music is somewhere on the beach, south-east. Watch out for the penguins. They are music critics.']],
  bjarne_thanks: [['Bjarne', 'MY MASTERPIECE! You saved RUSH Ø!'], ['Bjarne', 'Listen... (Bjarne plays faster than should be humanly possible.)'], ['Jon', 'That was beautiful. I think I am crying. Can axes cry?'], ['Bjarne', 'Take this. I found it inside my piano. Every hero needs more heart.']],
  bjarne_after: [['Bjarne', 'RUSH Ø! Again! From the top! (He does not stop playing.)']],
  revive: [['Jon', 'Voodoo bond! Get up, zombie! (Touch a runestone to recharge it.)']],
  juice: [['', 'You drank the Lingonberry Juice. Hearts restored!']],
  saved: [['', 'The runestone glows. Game saved. Hearts and voodoo bond restored.']],
  chapter_done: 'CHAPTER 1 COMPLETE',
  quips: ['da da da... (Rush E)', 'I\'m loyal!', 'World\'s best owner!', 'Ak ak ak', 'You can\'t get rid of me', 'Penguins. Ugh.', 'Bring me THUNDER!'],
};

const ITEMS = {
  key: { name: 'Small Key', icon: 'key', lines: [['', 'You got a SMALL KEY! It opens one locked door in this dungeon.']] },
  bigkey: { name: 'Big Key', icon: 'bigkey', lines: [['', 'You got the BIG KEY! It opens the boss door.']] },
  homing: { name: 'Homing Jon', icon: 'homing', lines: [
    ['', 'You got HOMING JON!'],
    ['Jon', 'I can SEE them now! Throw me and I lock on to enemies and crystals. And I fly way farther. You are welcome.'],
    ['', 'Throw Jon with X. He curves toward the nearest target.']] },
  thunder: { name: 'Thunder Rune', icon: 'thunder', lines: [
    ['', 'You got the THUNDER RUNE!'],
    ['Jon', 'Oh. Oh YES. I remember this. Walter carved it into me. Fill the rune meter, press C, and I come down like lightning!'],
    ['', 'Thunder Strike hits every enemy on the screen. Defeat enemies to fill the rune meter.']] },
  piece: { name: 'Piece of Heart', icon: 'piece', lines: [['', 'You got a PIECE OF HEART! Collect four to grow a new heart.']] },
  container: { name: 'Heart Container', icon: 'container', lines: [['', 'You got a HEART CONTAINER! Your life grew by one heart.']] },
  kr20: { name: '20 Kroner', icon: 'coin', lines: [['', 'You found 20 kroner!']] },
  juice: { name: 'Lingonberry Juice', icon: 'juice', lines: [['', 'LINGONBERRY JUICE! If your hearts run out, you drink it automatically.']] },
  shard: { name: 'Rune Shard', icon: 'shard', lines: [['', 'A RUNE SHARD! Your rune meter fills up.']] },
  heart3: { name: 'Heart Refill', icon: 'heart', lines: [['', 'Hearts refilled!']] },
  sheet: { name: 'Sheet Music', icon: 'sheet', lines: [['', 'You found BJARNE\'S SHEET MUSIC! It says "RUSH Ø" at the top. There are WAY too many notes.'], ['Jon', 'Bring it back to Bjarne in Fjordvik. The house on the right.']] },
  ship: { name: 'Toy Longship', icon: 'ship', lines: [['', 'You found SVEN\'S TOY LONGSHIP!'], ['Jon', 'Tiny Vikings. Adorable. Back to Sven at the market.']] },
};
