// All words in the game. Owen: edit freely. [speaker, text] pairs; speaker '' = narration.
const STORY = {
  intro: [
    ['Jon', 'Get up, you oaf!'],
    ['Owen', 'Oh yeah. Jon is a flying axe that can talk. If you think that\'s weird, he can also recite Rush E note for note, from memory.'],
    ['Jon', 'Come look at the table! I carved you something!'],
  ],
  plaque: [
    ['', '"WORLD\'S BEST OWNER OF A FLYING AND TALKING AXE NAMED JON"'],
    ['Jon', 'Well?'],
    ['Owen', 'Very nice of you Jon, I appreciate it.'],
    ['Jon', 'Are you gonna put it in our room?!?'],
    ['Owen', 'Um, sure...'],
    ['Jon', 'Well, I think we should get going. TO... (dramatic pause...) NORWAY!'],
    ['Owen', 'WHAT?! Norway is where I got you. It\'s also where I was killed and brought back to life.'],
    ['Jon', 'Exactly. Unfinished business. Grab your stuff. Door\'s at the bottom.'],
  ],
  poster: [['', 'A poster of a Viking longship. Under it, in marker: "OWEN\'S ROOM. NO PENGUINS."']],
  flight: [
    { art: 'plane', lines: [['', 'Flight 364. New York to Norway. Jon is in a checked bag down below.'], ['Owen', 'I tried not to think about my last time in Norway.']] },
    { art: 'cabin', lines: [['Attendant', 'Refreshments will come around once we reach a steady flying level.'], ['Owen', '(She gave me an odd look.)']] },
    { art: 'demon', lines: [['Owen', '"DEMON!!" my mind screamed.'], ['Attendant', 'Is everything alright, sir?'], ['Owen', 'Yep...']] },
    { art: 'cabin', lines: [['', 'I fell asleep. My dreams were incredibly weird. One was that I turned into a cow.']] },
    { art: 'demon', lines: [['Attendant', 'Any refreshments, sir?'], ['', 'Her nails grew into talons. Her teeth into fangs.'], ['Attendant', 'Wonderful...'], ['Owen', 'I tried to call Jon.']] },
    { art: 'land', lines: [['', '...and then the wheels hit the runway. Fjordvik, Norway.'], ['Owen', 'Was that a dream? It had to be a dream.']] },
  ],
  arrival: [
    ['Owen', 'When I got off the plane, the perfectly normal (it was a dream) flight attendant sent me off to the nearby subway station.'],
    ['Owen', 'There I could exchange U.S. dollars for kroner and hitch a ride for the forest, to search for a palace filled with penguins (I know, right?) and destroy it.'],
    ['Jon', '*thump* Ow. Who packs an axe UNDER a cello? Hello Señor! NORWAY!'],
    ['', 'The subway stairs are south-west, by the sign. Arrows/WASD move. Z swings Jon or talks. X throws Jon. Enter opens gear, Jon and the map.'],
  ],
  attendant_ok: [['Attendant', 'Welcome to Norway, sir! The subway station is just south-west. You can exchange your dollars there.'], ['Owen', '(Perfectly normal. Teeth: normal. Nails: normal. It was a dream. It was DEFINITELY a dream.)'], ['Attendant', 'Is everything alright, sir?'], ['Owen', 'Yep...']],
  commuter: [['Commuter', 'The train? Hasn\'t run since the penguins got in the tunnel. Take the taxi. Tell him Gunnar sent you. He won\'t care.']],
  taxi_out: [
    { art: 'taxi', lines: [['', 'The taxi rattles out of Fjordvik. Jon hums Rush E from inside the bag.'], ['Driver', 'The forest, eh? Nobody goes in there anymore. Muck up to your knees.']] },
    { art: 'taxi', lines: [['Driver', 'And the palace? Ha. Ice palace, full of penguins. My cousin saw it. He doesn\'t talk much now.'], ['Owen', 'I know, right?']] },
  ],
  taxi_back: [{ art: 'taxi_night', lines: [['Driver', 'Airport. Twenty kroner. Try not to bring any penguins.'], ['Jon', 'No promises.']] }],
  forest_arrival: [['', 'The taxi drops you at the edge of the forest and leaves fast.'], ['Owen', 'I trudged through the muck and grime on the floor. For about two hours.'], ['Jon', 'Two hours. Of MUCK. My handle is never going to be the same.'], ['', 'Muck slows you down. Tall grass hides things. Jon can cut both.']],
  log_scene: [
    ['', 'A log. Too high to step over and too low to duck under.'],
    ['Jon', 'Hello Señor! Ooh, that\'s a big log, want me to chop it?'],
    ['Owen', 'Jon...'],
    ['Jon', 'Three good chops. Swing me at it. This is my moment.'],
  ],
  log_chopped: [['Jon', 'TIMBER! Did you see that? Did you SEE that?'], ['Owen', 'I saw it, Jon.'], ['Jon', 'Best. Day. Ever. The palace is east. Through the snow. Let\'s go wreck it.']],
  cargo: [
    ['', 'A bench by the plane. You could sit for a minute. ...Something is scratching inside the cargo hold. Slowly. Like long fingernails.'],
    ['', 'A voice whispers your name through the metal. Then it laughs.'],
    ['Jon', 'Nope. Nope nope nope. We are NOT going in there yet. Come back when we are stronger.'],
  ],
  cargo_open: [['', 'You sit on the bench by the plane. It has been a long day. Your eyes close...'], ['', 'The dream again. The cargo hold. Red light. Something humming the safety announcement.'], ['Jon', 'This is a dream. You KNOW it\'s a dream. ...Why am I in it? Fine. Let\'s finish it.']],
  cargo_done: [['Jon', 'You slept like a rock. A rock that kicked. No more nightmares. I checked.']],
  attendant: [['Attendant', 'Welcome aboard, sir. Please remain seated.'], ['Attendant', 'Any... refreshments?'], ['Jon', 'She only shows up when the lights flicker! Watch for her claws, dodge the dash, then hit her while she\'s dizzy!']],
  attendant_down: [['Attendant', 'Wonderful... Chilly will... hear about... this...'], ['', 'She folds up like a napkin and blows away through an air vent. Everything goes white.'], ['', 'You wake up on the bench. Jon is poking you with his handle.'], ['Jon', 'You were saying "refreshments" in your sleep. Never again. Also: look what you were holding.']],
  cargo_later: [['Jon', 'The scratching stopped. That is somehow worse. (The Red-Eye side quest arrives in a later chapter.)']],
  astrid_1: [
    ['Astrid', 'So. The boy who pulled Jontuka out of the lake has come back. And still alive. Mostly.'],
    ['Owen', 'Undead voodoo magic zombie, actually.'],
    ['Astrid', 'Hm. Well. Listen. A bizillion years ago, a smith forged that axe in the volcano east of here.'],
    ['Astrid', 'Walther the Wise, we called him. Or was it Waldo? Wilbur? Nobody remembers his real name.'],
    ['Owen', 'I just call him Walter the Wonderful.'],
    ['Astrid', 'Then a Viking chieftain named Hank threw the axe in the lake so only Viking blood could pull it out.'],
    ['Astrid', 'He was hiding it from Chilly, the Frost Demon. Chilly wants Jontuka. With it, he could crack open the volcano and freeze the whole world.'],
    ['Astrid', 'Chilly cannot walk in daylight. So he possesses creatures that do not belong here. Like penguins.'],
    ['Jon', 'Told you.'],
    ['Astrid', 'His penguins have built themselves a PALACE of ice up the Frozen Path, north-east, past the Muck Forest. Whatever rules it sits on a throne at the top.'],
    ['Astrid', 'Take this. Every bit of coin helps. Lars at the market sells lingonberry juice. It brings you back from almost anything.'],
  ],
  astrid_2: [['Astrid', 'The Penguin Palace is up the Frozen Path, north-east. Mind the slippery floors. Penguins love ice.']],
  astrid_3: [
    ['Astrid', 'The Thunder Rune! Walter carved that rune for the axe himself. Jontuka remembers who he is.'],
    ['Astrid', 'And the thunder woke the old runes. The seal on the Drowned Barrow in the north-west foothills has broken.'],
    ['Astrid', 'That is Hank\'s tomb. Chilly has been sending frost into it. If Hank\'s ghost turns, he will come for the axe he hid.'],
  ],
  astrid_4: [['Astrid', 'You freed Hank. Then the next door is Walter\'s Forge, on the volcano road. It will open when the story is ready.']],
  barrow_enter: [['Jon', 'Wet. Dark. Smells like old Viking socks.'], ['Owen', 'This is Hank\'s tomb. The guy who threw you in a lake.'], ['Jon', 'And I am STILL not over it.']],
  fluffy_1: [['Fluffy', 'Woof!'], ['', 'A ghostly dog wags its whole body. Its tag says FLUFFY.'], ['Jon', 'Hank\'s dog! He wants us to follow him. West, I think. Something big is guarding a treasure that way.']],
  fluffy_2: [['Fluffy', 'Woof woof!'], ['Jon', 'He says dash across the water to the north. Hank is up there. And he says good job. I added that part.']],
  fluffy_after: [['Fluffy', '(Fluffy rolls over for belly rubs. Your hand goes right through him. He doesn\'t mind.)']],
  captain: [['Draugr Captain', 'NONE... SHALL... PASS... the treasure of Hank!'], ['Jon', 'Same trick as the knight: hit, hit! Or get behind him.']],
  hank: [['Hank', 'WHO... DISTURBS... HANK?'], ['Owen', 'It\'s me. Owen. I have your axe. Well, it has me.'], ['Hank', 'CHILLY\'S... FROST... I... cannot... stop...'], ['Jon', 'He\'s frozen solid. My blade bounces off! Owen, VOODOO DASH right through him to shatter the frost!']],
  hank_down: [['', 'The frost cracks and falls away. A tired old Viking ghost looks down at you.'], ['Hank', 'Thank you, boy. Chilly froze me to guard this place until the axe came home.'], ['Hank', 'I threw Jontuka in the lake to keep it from him. I am sorry it landed on you.'], ['Jon', 'It landed on HIM? It landed on ME. In a LAKE. For a BIZILLION years.'], ['Hank', 'The smith who forged you knows how to stop Chilly. Go to his forge on the volcano road.'], ['Hank', 'His real name was... no. I swore never to say it. And give Fluffy a pat for me.'], ['Fluffy', 'WOOF!']],
  lars: [['Lars', 'Velkommen! Lingonberry juice, rune shards, hearts. Walk up to a table and press Z to buy.']],
  sven_1: [['Sven', 'My big sister says if you cut bushes with an axe you find kroner. I saw a sparkly thing in the forest behind a ring of bushes.']],
  sven_2: [['Sven', 'There is another sparkly thing in the graveyard. In the far corner. I am NOT going in there.']],
  ingrid: [
    ['Ingrid', 'You swim in the lake, it spits you right back out. Lake\'s got manners, that one.'],
    ['Ingrid', 'Ever since the penguins showed up, I hear them at night. "Ak ak ak."'],
    ['Jon', '...that one was me.'],
  ],
  signs: {
    sign_airstrip: [['', 'FJORDVIK AIRSTRIP. Subway: south-west. Village: north-west. Beach: east.']],
    sign_subway: [['', 'FJORDVIK T-BANE (subway). Currency exchange inside. Taxis to the forest.']],
    sign_tbane: [['', 'T-BANE. Next train: NEVER (penguins in the tunnel). Taxi stand: east end of the platform.']],
    sign_fjordvik: [['', 'FJORDVIK. Population: 41 Vikings, 0 penguins (we hope).']],
    sign_cavern: [['', 'THE PENGUIN PALACE. No humans. No axes. No exceptions. Ak.']],
    sign_cavern_in: [['', 'Locked doors take a small key. The big door takes the BIG key. Crystals switch things.']],
    sign_beach: [['', 'HERE IS THE BEACH WHERE OWEN DIED. (He got better.)']],
    sign_poster: [['', 'A poster of a Viking longship. Under it, in marker: "OWEN\'S ROOM. NO PENGUINS."']],
    seal_barrow: [['', 'A stone door, sealed by a glowing rune. The DROWNED BARROW. Chapter 2.']],
    seal_forge: [['', 'A stone door, sealed by a glowing rune. WALTER\'S FORGE. Chapter 3.']],
    seal_peak: [['', 'A stone door, sealed by a glowing rune. The STORM PEAK. Chapter 4.']],
  },
  house: [['', 'Nobody answers. Someone inside is humming Rush E.']],
  cavern_enter: [['Owen', 'A palace. Filled with penguins. I know, right?'], ['Jon', 'It\'s FREEZING. And fancy. Stay off the ice if you like stopping. Let\'s wreck the place.']],
  pit_first: [['Jon', 'You fell in a hole. I would have flown. Just saying.']],
  locked: [['', 'Locked. You need a small key.']],
  bossdoor: [['', 'A huge door with a huge lock. You need the BIG key.']],
  knight: [['Jon', 'A penguin in ARMOR. Hit him from the side or the back. His shield blocks the front!']],
  king: [
    ['Penguin King', 'AK. AK AK. The axe. Give... me... the AXE.'],
    ['Owen', 'You\'re the one who killed me!'],
    ['Penguin King', 'That was my cousin. I am WORSE. Chilly made me KING.'],
    ['Jon', 'He belly-slides! Dodge him, let him smack the wall, THEN chop him while he\'s dizzy!'],
  ],
  king_down: [
    ['Penguin King', 'Ak... Chilly... will... find you...'],
    ['', 'The frost spirit flies out of the penguin and shatters. A very confused regular penguin waddles away.'],
    ['Jon', 'And THAT is how we do it in Norway.'],
  ],
  tapestry: [['', 'A woven tapestry: a huge Viking in a horned helmet hurls a glowing axe into a lake. Stitched underneath: "HANK DID THIS."']],
  bookshelf: [['', 'A thick book: "WALTER THE WONDERFUL: A Biography." Chapter 1, "His Real Name Was..."'], ['', 'The rest of the page is torn out. Somebody does NOT want you to know.']],
  rush_poster: [['', 'A hand-painted poster: "RUSH Ø. The fastest song ever written. Do not attempt. (Bjarne attempted.)"']],
  cave_carving: [['', 'Scratched into the rock: "FLUFFY WAS HERE. FLUFFY WAS A GOOD BOY." Paw prints run off into the dark.']],
  grave: [['', '"HERE LIES FLUFFY, HANK\'S DOG. GOOD BOY."'], ['Jon', 'Owen. The stone is loose. Push it. Push the dog grave.'], ['', 'The gravestone grinds aside. Stairs lead down into the dark!']],
  grave_open: [['Jon', 'Fluffy\'s secret tunnel. Good boy.']],
  sven_quest: [['Sven', 'Owen! I lost my toy longship in the Whispering Forest, north of the village. I hid it under a bush so the penguins wouldn\'t get it...'], ['Sven', '...and then I forgot which bush. Can you find it? Jon can cut bushes, right?']],
  sven_waiting: [['Sven', 'It\'s under one of the bushes in the forest. I think it\'s near the big path. Probably. Maybe.']],
  sven_thanks: [['Sven', 'MY LONGSHIP! You found it! Here, take my savings. And this juice. Mom says it\'s for emergencies, but this IS one.']],
  bjarne_quest: [['Bjarne', 'Ah, a visitor! I am Bjarne, the greatest musician in Fjordvik. Also the only one.'], ['Bjarne', 'I wrote the fastest song in the world: RUSH Ø. But a penguin sneezed and my sheet music blew all the way to the beach!'], ['Jon', 'Rush Ø? I know a song like that. I can recite it note for note.'], ['Bjarne', 'Then you understand! Please, bring back my music. The beach is south-east, past the lake.']],
  bjarne_waiting: [['Bjarne', 'My sheet music is somewhere on the beach, south-east. Watch out for the penguins. They are music critics.']],
  bjarne_thanks: [['Bjarne', 'MY MASTERPIECE! You saved RUSH Ø!'], ['Bjarne', 'Listen... (Bjarne plays faster than should be humanly possible.)'], ['Jon', 'That was beautiful. I think I am crying. Can axes cry?'], ['Bjarne', 'Take this. I found it inside my piano. Every hero needs more heart.']],
  bjarne_after: [['Bjarne', 'RUSH Ø! Again! From the top! (He does not stop playing.)']],
  revive: [['Jon', 'Voodoo bond! Get up, zombie! (Touch a runestone to recharge it.)']],
  juice: [['', 'You drank the Lingonberry Juice. Hearts restored!']],
  saved: [['', 'The runestone glows. Game saved. Hearts and voodoo bond restored.']],
  chapter_done: 'CHAPTER 2 COMPLETE',
  quips: ['da da da... (Rush E)', 'I\'m loyal!', 'World\'s best owner!', 'Ak ak ak', 'You can\'t get rid of me', 'Penguins. Ugh.', 'Bring me THUNDER!'],
};

// Jon's personality: short lines he says on his own. Jon is based on Owen's real best friend,
// so he's loyal, funny, bossy, and always on Owen's side. Edit or add lines freely.
const JON = {
  idle: ['Hello Señor!', 'da da da... (Rush E)', 'Owen. OWEN. We\'re burning daylight.', 'I could carve something while we wait.', 'Did you know I can recite Rush E? Because I can.', 'Standing still is how penguins get you.', 'Best friends don\'t make best friends wait.',
    'Fun fact: I\'m the sharpest thing in Norway. Fact.', 'Do zombies blink? You haven\'t blinked in a while.', 'I\'m not saying I\'m the brains of this operation. I\'m saying I\'m the blade.', 'If we stand here long enough, do we become a statue? Asking for me.',
    'Hank threw me in a LAKE, Owen. A whole lake. I\'m over it. I\'m not over it.', 'Walter named me Jöntuka. With the dots. The dots are important.', 'Hello Señor! ...I don\'t know why I say that. It feels right.', 'Is it weird that I can smell penguins? It\'s weird. Let\'s move.',
    'I had a dream I was a spoon. Worst dream. Let\'s go.', 'Quick question: who\'s carrying who here?', 'You know what this moment needs? A guitar solo. WAAAAH.', 'I don\'t have legs and I\'m still faster than you.'],
  sing: ['*humming* Dooon\'t stop... choppin\'...', '*humming* Cold as fjooord... you know that you are...', '*humming* WALK this fjord! Da na na na!', '*humming* Is this the real life? Is this just penguins?', '*humming* I want to break FREE... from this bag.', '*humming* Dream on, dream on, dream on... zombie dream on.', '*humming* We will, we will, CHOP you! *stomp stomp clap*', '*humming* Any way the wind blows... the penguins still come...', 'I\'ve been working on an air-guitar solo. No arms. It\'s mostly a feeling.', 'Juke box HERO! ...wait. Lake box hero. That\'s me.'],
  sleepy: ['zzz...', 'zzz... five more minutes... zzz', 'zzz... ak ak ak... zzz', 'zzz... no, Hank, not the lake... zzz', 'zzz... don\'t stop... believ... zzz', 'zzz... so sharp... so handsome... zzz'],
  wake: ['I was NOT asleep.', 'Huh? I was resting my blade.', 'Okay okay, I\'m up!', 'I was meditating. Axes meditate.', 'WHO\'S THERE. Oh. You. Hi.'],
  kill: ['Got one!', 'Chop!', 'Teamwork!', 'Easy.', 'Ha! Nailed it!', 'That\'s my best friend!', 'Boom. Sliced.', 'Did you see that? You saw that.', 'Another one for the sign!', 'Sorry! Not sorry.', 'Timber! ...wrong joke. Still counts.', 'I\'m a lumberjack and I\'m... no wait, I\'m the axe.'],
  streak: ['We are UNSTOPPABLE!', 'Three in a row! High five! ...I don\'t have hands.', 'Combo! I\'m counting!', 'Hat trick! Do I get a hat? Get me a hat.', 'Okay THAT was the chorus. Big finish!', 'Somebody write this down!'],
  hurt: ['Hey! Nobody hits my friend!', 'You okay?!', 'Ow ow ow. Wait, that was you.', 'Walk it off, zombie!', 'HEY. That\'s MY zombie.', 'Rude!', 'You\'re fine. You\'re already dead. Technically.', 'Okay, new plan: don\'t get hit.'],
  lowhp: ['Owen, you\'re looking extra dead.', 'Maybe drink some juice?', 'Careful! I need you!', 'Hearts. We need hearts.', 'You\'re greener than usual. Is that bad? That\'s bad.', 'If you fall over I can\'t pick you up. No arms. Please don\'t.', 'Cut some grass! Hearts hide in grass!'],
  thrown: ['WHEEEE!', 'I can FLY!', 'Incoming!', 'Fore!', 'Catch me catch me catch me!', 'I regret NOTHING!', 'Boomerang axe! It\'s a thing now!', 'Dream ooon!'],
  wall: ['Ow. Wall.', 'Who put that there?', 'I meant to do that.', 'The wall started it.', 'Note to self: walls are solid.', 'Ow. My face. I don\'t have a face. Ow.'],
  item: ['Ooh, shiny!', 'Put it in the pack!', 'Treasure! I love treasure!', 'Is it for me? It\'s for me.', 'Loot! Say it with me: LOOT!'],
  boss: ['We did it! Best team in Norway!', 'Told you we could do it.', 'That\'s going on the carved sign.', 'WE ARE THE CHAMPIONS, my friend! ...of this room.', 'Big finish! Lights! Confetti! No? Fine.'],
  water: ['Not the lake again...', 'I hate water. Long story.', 'Keep me away from that lake.', 'I don\'t float, Owen. I\'ve checked. Twice.', 'Rust. Rust is the enemy. Also penguins.'],
  penguin: ['Penguins. In NORWAY.', 'Ak ak ak. Sorry. Reflex.', 'I see a penguin. I hate it.', 'They waddle like they own the place.', 'Formal wear and no manners. Typical.', 'Why do they always look so SMUG?'],
  levelup: ['I feel STRONGER!', 'Level up! I\'m basically a sword now.', 'Friendship POWER!', 'Did I get shinier? I got shinier.', 'Walter would be SO proud. Pickles would... I mean Walter.', 'Is this what growing up feels like? I love it.', 'New level, same handsome.'],
  spin: ['SPIN TO WIN!', 'Wheeeee-ooo!', 'Tornado mode!', 'I\'m a blender! A VIKING blender!', 'Round and round and... I\'m dizzy. Worth it.'],
  log: ['Chop! Chop! Say it with me!', 'One more! Put your back into it! You have a back!', 'Hello Señor LOG. Goodbye Señor Log.', 'This is the best day of my life.'],
  muck: ['Ew. Ew ew ew. Muck.', 'Two hours of this, you said. TWO HOURS.', 'My handle. My beautiful handle. Mud.', 'Is this muck or grime? I need to know what I\'m stepping in. Being carried through.', 'Squelch. Squelch. Squelch. I hate the word squelch.'],
  grass: ['Mow it! Mow it all!', 'Free hearts live in grass. Science.', 'I\'m a lawnmower now. Dreams do come true.', 'Snip snip!'],
  snow: ['Cold as fjord. Cold as ICE. Get it? ...Cold.', 'I can\'t feel my blade. I don\'t have nerves, but still.', 'Snow is just lake that gave up.', 'Brrr. Carry me somewhere warm. Like inside a penguin.'],
  night: ['Ooh, stars. Make a wish. Wish for fewer penguins.', 'Fireflies! Tiny lanterns with no job.', 'Night time. Chilly time. Stay sharp. I\'ll stay sharp for both of us.', 'Is it bedtime? Zombies don\'t sleep. Axes don\'t sleep. Great. We\'re a great team.'],
  dawn: ['Sunrise! Chilly hates this. Rub it in.', 'Morning! You look terrible. In a zombie way. It\'s fine.'],
  tablet: ['A rune tablet! Old words. Hank\'s handwriting is awful.', 'Secret lore! I love lore. Read it twice.', 'Who carves on rocks? Hank. Hank carves on rocks.'],
  taxi: ['I rode in a BAG. Never again. Until the way back.', 'Twenty kroner! Highway robbery. Fjord-way robbery.', 'The driver said the forest eats people. He said it like a joke. I don\'t think it was a joke.'],
  chest: ['Chests are just boxes that respect you.', 'Open it open it open it!', 'If it\'s socks I\'m leaving.'],
  beetle: ['Armor. Of course it has armor. THROW me at it!', 'Flip it! Flip it like a pancake! Then chop the pancake!', 'That beetle is wearing more plating than Hank.'],
  slime: ['Blue goo. Don\'t let it touch me. I\'ll smell like goo.', 'It split! That\'s cheating! Chop it twice!', 'Jello with ambitions.'],
  spore: ['A mushroom is SPITTING at us. A mushroom.', 'It hides under its own hat. Coward. Get close, then back off, then CHOP.', 'Never trust a fungus with eyes.'],
  guard: ['Royal Guards! Gold penguins with shields. Of course.', 'Get behind him! Penguins can\'t turn fast. Short legs.', 'He\'s wearing a bucket. A GOLD bucket.'],
  snowpeng: ['Snow penguins! They\'re FAST. Why are they fast?!', 'Zigzag penguin. Zigzag penguin. Hold still, bird!', 'They skate. Penguins that skate. I\'m done.'],
  frost: ['Ice ice, baby penguin.', 'Frozen! Now CHOP. Chop chop chop!', 'Cold as fjord. Literally this time.'],
  mend: ['Ahh. Hearts. Feel better? You look less green.', 'Mended! Hank\'s rune works. Mostly used it on the dog, apparently.'],
  lutefisk: ['You ATE it. You actually ate it. I can smell it from HERE.', 'Lutefisk. Jelly fish. Not a jellyfish. Jelly. Fish. Why.', 'I need a minute. I need a minute away from you.'],
  dark: ['Dark. Hold me up high. I glow. You\'re welcome.', 'If something grabs you, swing me. If something grabs ME, swing harder.'],
  area: {
    home: 'Our room! With MY sign in it.',
    overworld: 'Norway! Smell that? Fjords.',
    village: 'Fjordvik! Lars has juice.',
    cavern: 'A penguin PALACE. Fancy. Hate it.',
    subway: 'Subway! Smells like... subway.',
    forest: 'The Muck Forest. Nobody said muck. Somebody should have said muck.',
    frozen: 'The Frozen Path! Cold as fjord, baby.',
    barrow: 'Hank\'s tomb. Be cool.',
    redeye: 'I don\'t like this. At all.',
    secret_cave: 'Fluffy\'s tunnel! Good boy.',
    astrid_house: 'Wipe your feet.',
    bjarne_house: 'It smells like music in here.',
  },
};

const ITEMS = {
  key: { name: 'Small Key', icon: 'key', lines: [['', 'You got a SMALL KEY! It opens one locked door in this dungeon.']] },
  bigkey: { name: 'Big Key', icon: 'bigkey', lines: [['', 'You got the BIG KEY! It opens the boss door.']] },
  homing: { name: 'Homing Jon', icon: 'homing', lines: [
    ['', 'You got HOMING JON!'],
    ['Jon', 'I can SEE them now! Throw me and I lock on to enemies and crystals. And I fly way farther. You are welcome.'],
    ['', 'Throw Jon with X. He curves toward the nearest target.']] },
  thunder: { name: 'Thunder Rune', icon: 'thunder', lines: [
    ['', 'You got the THUNDER RUNE!'],
    ['Jon', 'Oh. Oh YES. I remember this. Walter carved it into me. Fill the rune meter, press C, and I come down like lightning!'],
    ['', 'Thunder Strike hits every enemy on the screen. Defeat enemies to fill the rune meter.']] },
  piece: { name: 'Piece of Heart', icon: 'piece', lines: [['', 'You got a PIECE OF HEART! Collect four to grow a new heart.']] },
  container: { name: 'Heart Container', icon: 'container', lines: [['', 'You got a HEART CONTAINER! Your life grew by one heart.']] },
  kr20: { name: '20 Kroner', icon: 'coin', lines: [['', 'You found 20 kroner!']] },
  juice: { name: 'Lingonberry Juice', icon: 'juice', lines: [['', 'LINGONBERRY JUICE! If your hearts run out, you drink it automatically.']] },
  shard: { name: 'Rune Shard', icon: 'shard', lines: [['', 'A RUNE SHARD! Your rune meter fills up.']] },
  heart3: { name: 'Heart Refill', icon: 'heart', lines: [['', 'Hearts refilled!']] },
  dash: { name: 'Voodoo Dash', icon: 'dash', lines: [['', 'You got the VOODOO DASH!'], ['Jon', 'Our voodoo bond just leveled up. Press Shift (or F) and you zip forward like a zombie rocket.'], ['', 'While dashing you can\'t be hurt. You pass through enemies, purple spirit barriers, and short stretches of water or pits.']] },
  kr50: { name: '50 Kroner', icon: 'gold', lines: [['', 'You found 50 kroner!']] },
  horn: { name: 'Demon Horn', icon: 'horn', lines: [['', 'You got the DEMON HORN! It came from the flight attendant\'s... luggage.'], ['Jon', 'Blow it with V. Costs half the rune meter. Regular enemies run away screaming. Bosses are too proud to care.']] },
  frost: { name: 'Frost Rune', icon: 'frost', lines: [['', 'You got the FROST RUNE!'], ['Jon', 'Ooh, cold one. Walter carved this on a bad day. Press C and everything near us freezes solid. Then chop the ice. Double damage.'], ['', 'Spells cost rune meter. Cycle spells with Q or the left shoulder button. See them in the SPELLS page.']] },
  fire: { name: 'Fire Rune', icon: 'fire', lines: [['', 'You got the FIRE RUNE! Somebody dropped it on the tracks.'], ['Jon', 'FIRE. I shoot FIRE now. Bushes, grass, penguins. Especially penguins.'], ['', 'Press C to throw a fireball. It burns bushes and tall grass in its path.']] },
  mend: { name: 'Mend Rune', icon: 'mend', lines: [['', 'You got the MEND RUNE!'], ['Astrid', 'Hank\'s own healing rune. He used it mostly on the dog.'], ['Jon', 'Two hearts for six rune. Don\'t waste it on paper cuts.']] },
  salmon: { name: 'Smoked Salmon', icon: 'salmon', lines: [['', 'SMOKED SALMON! Eat it from the BAG to heal two hearts.']] },
  lutefisk: { name: 'Lutefisk', icon: 'lutefisk', lines: [['', 'LUTEFISK. Fish soaked in lye until it jiggles. Heals everything.'], ['Jon', 'Keep it away from me. I\'m serious. I will rust.']] },
  bearclaw: { name: 'Bear Claw Charm', icon: 'bearclaw', lines: [['', 'You got the BEAR CLAW CHARM! Wear it from the BAG: chops crit twice as often.']] },
  boots: { name: "Fisherman's Boots", icon: 'boots', lines: [['', 'You got FISHERMAN\'S BOOTS! Wear them from the BAG: muck can\'t slow you.'], ['Jon', 'Two hours of muck. TWO HOURS. And the boots were RIGHT THERE.']] },
  cloak: { name: 'Wool Cloak', icon: 'cloak', lines: [['', 'You got the WOOL CLOAK! Wear it from the BAG: it shrugs off some hits.']] },
  tooth: { name: 'Troll Tooth', icon: 'tooth', lines: [['', 'You got a TROLL TOOTH! Wear it from the BAG: enemies drop more.'], ['Jon', 'Whose tooth? WHOSE TOOTH, LARS?']] },
  sheet: { name: 'Sheet Music', icon: 'sheet', lines: [['', 'You found BJARNE\'S SHEET MUSIC! It says "RUSH Ø" at the top. There are WAY too many notes.'], ['Jon', 'Bring it back to Bjarne in Fjordvik. The house on the right.']] },
  ship: { name: 'Toy Longship', icon: 'ship', lines: [['', 'You found SVEN\'S TOY LONGSHIP!'], ['Jon', 'Tiny Vikings. Adorable. Back to Sven at the market.']] },
};
